/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FederationService } from "../federation.service";
import { FederationCreateInput } from "./FederationCreateInput";
import { Federation } from "./Federation";
import { FederationFindManyArgs } from "./FederationFindManyArgs";
import { FederationWhereUniqueInput } from "./FederationWhereUniqueInput";
import { FederationUpdateInput } from "./FederationUpdateInput";

export class FederationControllerBase {
  constructor(protected readonly service: FederationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Federation })
  async createFederation(
    @common.Body() data: FederationCreateInput
  ): Promise<Federation> {
    return await this.service.createFederation({
      data: data,
      select: {
        contactInformation: true,
        country: true,
        createdAt: true,
        description: true,
        id: true,
        logo: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Federation] })
  @ApiNestedQuery(FederationFindManyArgs)
  async federations(@common.Req() request: Request): Promise<Federation[]> {
    const args = plainToClass(FederationFindManyArgs, request.query);
    return this.service.federations({
      ...args,
      select: {
        contactInformation: true,
        country: true,
        createdAt: true,
        description: true,
        id: true,
        logo: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Federation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async federation(
    @common.Param() params: FederationWhereUniqueInput
  ): Promise<Federation | null> {
    const result = await this.service.federation({
      where: params,
      select: {
        contactInformation: true,
        country: true,
        createdAt: true,
        description: true,
        id: true,
        logo: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Federation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFederation(
    @common.Param() params: FederationWhereUniqueInput,
    @common.Body() data: FederationUpdateInput
  ): Promise<Federation | null> {
    try {
      return await this.service.updateFederation({
        where: params,
        data: data,
        select: {
          contactInformation: true,
          country: true,
          createdAt: true,
          description: true,
          id: true,
          logo: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Federation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFederation(
    @common.Param() params: FederationWhereUniqueInput
  ): Promise<Federation | null> {
    try {
      return await this.service.deleteFederation({
        where: params,
        select: {
          contactInformation: true,
          country: true,
          createdAt: true,
          description: true,
          id: true,
          logo: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
