/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Club } from "./Club";
import { ClubCountArgs } from "./ClubCountArgs";
import { ClubFindManyArgs } from "./ClubFindManyArgs";
import { ClubFindUniqueArgs } from "./ClubFindUniqueArgs";
import { CreateClubArgs } from "./CreateClubArgs";
import { UpdateClubArgs } from "./UpdateClubArgs";
import { DeleteClubArgs } from "./DeleteClubArgs";
import { ClubService } from "../club.service";
@graphql.Resolver(() => Club)
export class ClubResolverBase {
  constructor(protected readonly service: ClubService) {}

  async _clubsMeta(
    @graphql.Args() args: ClubCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Club])
  async clubs(@graphql.Args() args: ClubFindManyArgs): Promise<Club[]> {
    return this.service.clubs(args);
  }

  @graphql.Query(() => Club, { nullable: true })
  async club(@graphql.Args() args: ClubFindUniqueArgs): Promise<Club | null> {
    const result = await this.service.club(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Club)
  async createClub(@graphql.Args() args: CreateClubArgs): Promise<Club> {
    return await this.service.createClub({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Club)
  async updateClub(@graphql.Args() args: UpdateClubArgs): Promise<Club | null> {
    try {
      return await this.service.updateClub({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Club)
  async deleteClub(@graphql.Args() args: DeleteClubArgs): Promise<Club | null> {
    try {
      return await this.service.deleteClub(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
